version: 2

before:
  hooks:
    - rustup default stable
    - cargo fetch --locked

builds:
  - builder: rust
    id: yafetch
    binary: yafetch
    tool: cargo
    command: build
    flags:
      - --release
      - --bin
      - yafetch
    targets:
      - aarch64-apple-darwin
    env:
      - CARGO_TARGET_AARCH64_APPLE_DARWIN_LINKER=clang

homebrew_casks:
  - name: yafetch
    repository:
      owner: pkarpovich
      name: homebrew-apps
    commit_author:
      name: Pavel Karpovich
      email: pavel.karpovich@outlook.com
    homepage: https://github.com/pkarpovich/yafetch
    description: "Yet another neofetch"
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yafetch"]
          end

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

